### ISSUE TITLE
Menu color

### ISSUE THREAD

**Issue by Bob-dot360** [bonzibudd/Fluent-Metro#163]
Hi! I like to combine apps with light theme and dark Start menu and taskbar. It is possible, when I choose "[Custom](https://miro.medium.com/max/2400/0*THohOxsOAjrZoY2N.jpg)" in Windows color settings. But, Fluent-Metro orientates on the apps theme. So, I have dark taskbar and white Start menu when I chose "use system theme" in skins settings. Could you make your skin orientates on the color of the taskbar, not applications?

[Start Menu screen](https://i.imgur.com/8EL7fto.jpg)

**Comment by bonzibudd** [comment]
Fluent-Metro uses the `SystemText` and `SystemBackground` colors for that option, so under normal circumstances, it should match the Taskbar, and not the apps color. Are you using any custom theming software for the Taskbar or visual styles? If not, it is possible that Microsoft removed or changed the elements that the skin relies on, making them match the wrong setting. If you could, I would also like you to attach your Windows 10 build number and screenshots of other combinations of the system/apps color options, so I can look into this some more.

**Comment by Bob-dot360** [comment]
I noticed that the skin does not determine which theme I have chosen anyway, no matter if everything is dark or not.
[Screen 1](https://i.imgur.com/d0grcSv.jpg), [Screen 2](https://i.imgur.com/gRRddIr.jpg) (tested in Virtualbox, because of this, the parameters look like this)

**Comment by bonzibudd** [comment]
@Bob-dot360 I think I see the issue.

Because of some naming conflicts with the color palettes, the “Immersive” Windows 10 colors are not supported on Classic Shell 4.3.1 and older. In order to use the immersive colors, you have to upgrade to Open-Shell 4.4.160 or later. You can directly upgrade your existing installation with the executable on the GitHub [Releases](https://github.com/Open-Shell/Open-Shell-Menu/releases) page.

**Comment by Bob-dot360** [comment]
Thank you! I got updated and everything works correctly
