### ISSUE TITLE
Set custom transparency value?

### ISSUE THREAD

**Issue by GanerCodes** [bonzibudd/Fluent-Metro#168]
I'm digging around in the skin file and I can't find out how to change the opacities to custom values. I tried a bunch of image swaps and variable edits in resource hacker and I just can't figure it out

**Comment by bonzibudd** [comment]
The transparency is built in to the menu’s background PNG image, so it’s not easily possible to have more than a few transparency values. However, you can modify the `Glass opacity` setting under `Menu Look` to slightly change the opacity within the range of the background image.

**Comment by GanerCodes** [comment]
How do I change the built-in PNG image? Is it just adding a file to the Image folder in resourcehacker?

**Comment by bonzibudd** [comment]
There are several different menu background images that are used when different options are selected, and the numbers for those resource numbers are defined by the `main_bitmap_mask` items, and additionally the `main_bitmap_jump_mask` and `main_bitmap_search_mask` items are also used in the Windows 7-style skin. You can add a new background image by adding it to the `IMAGE` folder and re-assigning the number for the resource where needed. If you’re not already familiar with skinning, the [tutorial](http://www.classicshell.net/tutorials/skintutorial.html) may help some with the terms and structure.

Also note that Fluent-Metro uses very specific mask colors in order to achieve the automatic colorization, so keep that in mind when making the background picture. If you think it would be easier, you could just edit the existing images by decreasing the opacity of the transparent sections, and then you wouldn’t need to re-assign any of the images or worry about colorization. I probably won’t be able to help much more than that, but hopefully that gives you an idea of where to start.
